
set a = createobject("wscript.shell")

mytxt1=inputbox("Type first message here!","Type some text 1","i can't hear you bro")
mytxt2=inputbox("Type second message here","Type some text 2","How are you?")
mytxt3=inputbox("Type third message here","Type some text 3","Yo can i play whit you, I am good")
mytxt4=inputbox("Type fourth message here","Type some text 4","I am Chilling out")
mytxt5=inputbox("Type five message here","Type some text 5","hahahahahaha")
mytxt6=inputbox("Type six message here","Type some text 6","Yo i be back")
mytxt7=inputbox("Type seven message here","Type some text 7","Bdw i love your stream")
mytxt8=inputbox("Type eight message here","Type some text 8","Keep it up my guy!")
mytxt9=inputbox("Type nine message here","Type some text 9","You Trippin hard dude")
mytxt10=inputbox("Type ten message here","Type some text 10","Am I Weird lol?")
mynum=inputbox("How many times to send the text?","spamnumber","20") 
myspeed=inputbox("How fast to spam..In milisecs! 1000=1sec.","delay","9000") 
mywait=inputbox("Time to wait proir to sending the spam msg in secs","Wait?","3")

msgbox("You have " & mywait & " secs to put focus on your target text area!")
wscript.sleep (mywait*1000) 
for i=1 to mynum 		
	a.sendkeys (mytxt1)       
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)
	a.sendkeys (mytxt2)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt3)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt4)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt5)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt6)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt7)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt8)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt9)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt10)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
next
strlol = ("- Spam Bot by: RavelCros_Cro // Attack Finished! - ")
	a.sendkeys (strlol)   
	a.sendkeys ("{ENTER}")
msgbox("Finished Spamming!")
